### PR TITLE
Add German translation

### PR DESCRIPTION
**Pull request by steffenrapp**
Translations are from www.freeair-connect.de where available.

### CODE REVIEW

**Comment by mampfes** [comment]
Vielen Dank.

**Comment by steffenrapp** [comment]
Danke für die nice Integration!

**Comment by grericht** [comment]
How can i get the German Translation?
Thank for this nice add-on!

**Comment by mampfes** [comment]
They are already installed and automatically selected if you change the language in HA.

**Comment by grericht** [comment]
i changed from english to german but there ist still no german translation. did i have to delete and reconect the device?

**Comment by mampfes** [comment]
No, there is no extra action needed. I tested it on my box just now and it works for english and german. How did you install the integration? Did you use HACS and did you install the latest version?

**Comment by grericht** [comment]
dont know what is the problem.
i now deleted my 2 devices and then deletet the integration.
now trying to reinstall but getting the following mistake in german:
"Fehler
Diese Integration unterstützt keine Konfiguration über die Benutzeroberfläche. Wenn du diesem Link von der Home Assistant-Website gefolgt bist, stelle sicher, dass du die neueste Version von Home Assistant ausführst."
newest ha version is installed. using haos in proxmox.

**Comment by mampfes** [comment]
@grericht How did you install the integration? I recommend to use HACS. You also "reinstall" it there.

**Comment by steffenrapp** [comment]
@grericht what exactly is missing? Not everything was translatable. I think entity names still are English only. You can check in the code what has been translated and if you can see these translations in German?

**Comment by grericht** [comment]
sorry. everything works fine. 
I had wrongly assumed that the entities were also named in German and not “just” the values
thank u!

**Pull request merged**
